### PR TITLE
Makes Dark Mode Switcher functional. Fixes #21

### LINKED ISSUE #21: Dark mode switcher not working
Dark/Light mode switcher exists, but not functional

### PR DESCRIPTION
**Pull request by maccyber**
This makes the Dark Mode Switcher functional.

darkmode

### CODE REVIEW

**Comment by islamCodehood** [comment]
Thanks, @maccyber for the PR, and the screenshot. I will review the PR soon and merge it.

File: src/App.js [hunk 1]
```diff
@@ -59,7 +63,8 @@ function App() {
   };
   return (
     <div className="App">
-      <ThemeProvider theme={globalTheme}>
+      <ThemeProvider theme={appliedTheme}>
+        <CssBaseline />
```
Comment (islamCodehood) [inline src/App.js:67]: Great adding the CssBaseLine Mui component 👍

File: src/App.js [hunk 2]
```diff
@@ -36,6 +34,12 @@ function App() {
   const [mentors, setMentors] = useState(mentorsList);
   const [darkMode, setDarkMode] = useState(false);
 
+  const appliedTheme = createMuiTheme({
```
Comment (islamCodehood) [inline src/App.js:37]: I would like to change the basic theme too. I am gonna open an issue for that and would like to see some suggestions on the color palettes. I 'd like to assign this to you.

**Review by islamCodehood — APPROVED** [review]
