### PR TITLE
ui-fix: remove horizontal scroll

### LINKED ISSUE #58: fix extra space to the right of the page
Extra space to the right of the page as in the image.

Required is to know the reason for it and figure out a way to remove it.

### PR DESCRIPTION
**Pull request by mohamednajiub**

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -12,6 +13,7 @@ import {
   createMuiTheme,
   ThemeProvider,
   CssBaseline,
+  spac
```
Comment (islamCodehood) [inline src/App.js:16]: I think this is a typo, buddy.
I'm gonna remove it.

File: src/App.js [hunk 2]
```diff
@@ -173,11 +174,12 @@ function App() {
...
-    <div className='App'>
-      <ThemeProvider theme={appliedTheme}>
-        <CssBaseline />
-        <AppBar position='static' className={classes.appBar}>
-          <Toolbar>
+    <ThemeProvider theme={appliedTheme}>
+      <CssBaseline />
+
+      <AppBar position="static" className={classes.appBar}>
+        <Container maxWidth='lg'>
```
Comment (islamCodehood) [inline src/App.js:181]: Great usage Container component. You opened my eyes to a new opportunities.
Thanks @mohamednajiub

**Review by islamCodehood — APPROVED** [review]
Thanks for your PR, @mohamednajiub  👌 
Some behavior has changed regarding centering cards with smaller viewports. But it is ok, I will fix this.
